name: Node

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/node.yml"
            - "**/*.js"
            - "**/*.ts"
            - "**/package.json"
            - "**/tsconfig.json"
            - "pnpm-lock.yaml"
            - "pnpm-workspace.yaml"

    pull_request:
        branches:
            - main
        paths:
            - ".github/workflows/node.yml"
            - "**/*.js"
            - "**/*.ts"
            - "**/package.json"
            - "**/tsconfig.json"
            - "pnpm-lock.yaml"
            - "pnpm-workspace.yaml"

jobs:
    build:
        name: pnpm build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node v${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: pnpm install
              run: pnpm install
            - name: pnpm build
              run: pnpm build
